<?php if ( $this->canShowFieldset() ) : ?>
    <li id="<?php echo $this->getFieldsetId(); ?>" class="<?php echo $this->getFieldsetClass(); ?>">
        
        <?php /* fieldset title */ ?>
        <?php if ( $this->canShowTitle() ) : ?>
            <h2 class="legend fieldset-title">
                <?php echo $this->getFieldsetTitle(); ?>
            </h2>
        <?php endif; ?>
        
        <ul class="form-list fieldset-fields">
            <?php foreach ( $this->getFields() as $field ) : ?>
                <?php echo $this->getFieldHtml($field); ?>
            <?php endforeach; ?>
        </ul>
    </li>
<?php endif; ?>
