<?php if ( $this->hasErrors() ) : ?>
    <div>
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <?php foreach ( $this->getErrors() as $error ) : ?>
                        <li>
                            <span><?php echo $error; ?></span>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </div>
<?php endif; ?>
