<li id="<?php echo $this->getFieldId(); ?>" class="<?php echo $this->getFieldClass(); ?>">
    
    <label <?php echo $this->isInputRequired() ? 'class="required"' : ''; ?> >
        <?php echo $this->getFieldTitle(); ?>
        
        <?php if ( $this->isInputRequired() ) : ?>
            <em class="required">*</em>
        <?php endif; ?>
        
        <?php if ( $this->canShowHint() ) : ?>
            <span class="field-hint">
                (<a href="javascript:void(0);">help?</a>)
                <p><?php echo $this->getFieldHint(); ?></p>
            </span>
        <?php endif; ?>
    </label>
    
    <?php echo $this->getErrorsHtml(); ?>
    
    <div class="control">
        <div class="input-box">
            <input type="hidden" name="<?php echo $this->getFieldName(); ?>" value="0" />
            <input 
                value="1"
                id="<?php echo $this->getInputId(); ?>"
                class="<?php echo $this->getCssClass(); ?>"
                name="<?php echo $this->getFieldName(); ?>"
                title="<?php echo $this->getFieldTitle(); ?>"
                type="<?php echo $this->getFieldType(); ?>"
                
                <?php echo $this->getFieldValue() ? 'checked' : '' ?>
                >
        </div>
        <label for="<?php echo $this->getFor(); ?>" >
            <?php echo $this->getFieldLabel(); ?>
        </label>
    </div>
    
    <?php if ( $this->canShowComment() ) : ?>
        <div class="field-comment">
            <p><?php echo $this->getFieldComment(); ?></p>
        </div>
    <?php endif; ?>
</li>
