<li id="<?php echo $this->getFieldId(); ?>" class="<?php echo $this->getFieldClass(); ?>">
    <label for="<?php echo $this->getFor(); ?>" <?php echo $this->isInputRequired() ? 'class="required"' : ''; ?> >
        <?php echo $this->getFieldLabel(); ?>
        <?php if ( $this->isInputRequired() ) : ?>
            <em class="required">*</em>
        <?php endif; ?>
    </label>
    <div class="input-box">
        <input 
            id="<?php echo $this->getInputId(); ?>"
            class="input-text <?php echo $this->getCssClass(); ?>"
            name="<?php echo $this->getFieldName(); ?>"
            value="<?php echo $this->getFieldValue(); ?>"
            title="<?php echo $this->getFieldTitle(); ?>"
            type="<?php echo $this->getFieldType(); ?>"
            
            <?php echo $this->isInputRequired()  ? 'required'            : '';                     ?>
            <?php echo $this->isAutoCapitalise() ? 'autocapitalize="on"' : 'autocapitalize="off"'; ?>
            <?php echo $this->isAutoCorrect()    ? 'autocorrect="on"'    : 'autocorrect="off"';    ?>
            <?php echo $this->isAutoComplete()   ? 'autocomplete="on"'   : 'autocomplete="off"';   ?>
            <?php echo $this->isSpellcheck()     ? 'spellcheck="true"'   : 'spellcheck="false"';   ?>
            >
    </div>
    
    <?php if ( $this->canShowComment() ) : ?>
        <div class="field-comment">
            <p><?php echo $this->getFieldComment(); ?></p>
        </div>
    <?php endif; ?>
    
    <?php if ( $this->canShowHint() ) : ?>
        <div class="field-hint">
            <p><?php echo $this->getFieldHint(); ?></p>
        </div>
    <?php endif; ?>
    
</li>
