<li id="<?php echo $this->getFieldId(); ?>" class="<?php echo $this->getFieldClass(); ?>">
    
    <?php echo $this->getErrorsHtml(); ?>
    
    <div class="field-head">
        <label for="<?php echo $this->getFor(); ?>" <?php echo $this->isInputRequired() ? 'class="required"' : ''; ?> >
            <?php echo $this->getFieldLabel(); ?>
            <?php if ( $this->isInputRequired() ) : ?>
                <em class="required">*</em>
            <?php endif; ?>
            
            <?php if ( $this->canShowHint() ) : ?>
                <span class="field-hint">
                    (<a href="javascript:void(0);">help?</a>)
                    <p><?php echo $this->getFieldHint(); ?></p>
                </span>
            <?php endif; ?>
        </label>
    </div>
    
    <div class="field-body">
        <div class="input-box">
            <input <?php echo $this->getInputAttributes(); ?> >
        </div>
        
        <?php if ( $this->canShowComment() ) : ?>
            <div class="field-comment">
                <p><?php echo $this->getFieldComment(); ?></p>
            </div>
        <?php endif; ?>
    </div>
</li>
